language: ruby
sudo: false
cache: bundler
language: ruby
env:
  - SOLIDUS_BRANCH=v1.0   DB=mysql
  - SOLIDUS_BRANCH=v1.1   DB=mysql
  - SOLIDUS_BRANCH=v1.2   DB=mysql
  - SOLIDUS_BRANCH=master DB=mysql
  - SOLIDUS_BRANCH=v1.0   DB=postgres
  - SOLIDUS_BRANCH=v1.1   DB=postgres
  - SOLIDUS_BRANCH=v1.2   DB=postgres
  - SOLIDUS_BRANCH=master DB=postgres
rvm:
  - 2.1.8
